
brands = ['bmw', 'dacia', 'daewoo', 'daihatsu', 'datsun', 'derways', 'dodge', 'dong-feng', 'exeed', 'enovate', 'faw', 'ferrari', 'fiat', 'ford', 'foton', 'gac', 'gmc', 'geely', 'genesis', 'gonow', 'great-wall', 'hafei', 'haima', 'hanteng', 'haval', 'hiphi', 'honda', 'hongqi', 'huanghai', 'hummer', 'infiniti', 'iran-khodro', 'isuzu', 'jac', 'jmc', 'jaguar', 'jeep', 'jetour', 'jetta', 'jin-bei', 'kaiyi', 'karry', 'kia', 'lamborghini', 'lancia', 'land-rover', 'leap-motor', 'lexus', 'li', 'lifan', 'lincoln', 'lotus', 'lucid', 'mg', 'maserati', 'maxus', 'maybach', 'mazda', 'mercedes-benz', 'mercedes-maybach', 'mercury', 'mini', 'mitsubishi', 'nio', 'neta', 'nissan', 'opel', 'peugeot', 'plymouth', 'polestar', 'pontiac', 'porsche', 'puch', 'radar', 'ravon', 'renault', 'samsung', 'rivian', 'rolls-royce', 'rover', 'saic', 'saab', 'saturn', 'scion', 'seat', 'seres', 'shuanghuan', 'skoda', 'smart', 'ssang-yong', 'subaru', 'suzuki', 'tank', 'tesla', 'tianma', 'toyota', 'volkswagen', 'volvo', 'voyah', 'wanfeng', 'weltmeister', 'wuling', 'xpeng', 'zx', 'zeekr', 'zotye', 'vaz', 'vis', 'gaz', 'zaz', 'ij', 'luaz', 'moskvich', 'raf', 'retro-automobiles', 'smz', 'tagaz', 'uaz']

_brands = {
#   "acura": "acura",
#   "alfa-romeo": "alfa romeo",
#   "aro": "aro",
#   "audi": "audi",
#   "avatr": "avatr",
#   "baic": "baic",
  "bmw": "bmw",
#   "byd": "byd",
#   "bajaj": "bajaj",
#   "bentley": "bentley",
#   "brilliance": "brilliance",
#   "bugatti": "bugatti",
#   "buick": "buick",
#   "cadillac": "cadillac",
#   "changan": "changan",
#   "chery": "chery",
#   "chevrolet": "chevrolet",
#   "chrysler": "chrysler",
#   "citroen": "citroen",
  "dacia": "dacia",
  "daewoo": "daewoo",
  "daihatsu": "daihatsu",
  "datsun": "datsun",
  "derways": "derways",
  "dodge": "dodge",
  "dong-feng": "dongfeng",
  "exeed": "exeed",
  "enovate": "enovate",
  "faw": "faw",
  "ferrari": "ferrari",
  "fiat": "fiat",
  "ford": "ford",
  "foton": "foton",
  "gac": "gac",
  "gmc": "gmc",
  "geely": "geely",
  "genesis": "genesis",
  "gonow": "gonow",
  "great-wall": "great wall",
  "hafei": "hafei",
  "haima": "haima",
  "hanteng": "hanteng",
  "haval": "haval",
  "hiphi": "hiphi",
  "honda": "honda",
  "hongqi": "hongqi",
  "huanghai": "huanghai",
  "hummer": "hummer",
#   "hyundai": "hyundai",
  "infiniti": "infiniti",
  "iran-khodro": "iran khodro",
  "isuzu": "isuzu",
  "jac": "jac",
  "jmc": "jmc",
  "jaguar": "jaguar",
  "jeep": "jeep",
  "jetour": "jetour",
  "jetta": "jetta",
  "jin-bei": "jin bei",
  "kaiyi": "kaiyi",
  "karry": "karry",
  "kia": "kia",
  "lamborghini": "lamborghini",
  "lancia": "lancia",
  "land-rover": "land rover",
  "leap-motor": "leap motor",
  "lexus": "lexus",
  "li": "li",
  "lifan": "lifan",
  "lincoln": "lincoln",
  "lotus": "lotus",
  "lucid": "lucid",
  "mg": "mg",
  "maserati": "maserati",
  "maxus": "maxus",
  "maybach": "maybach",
  "mazda": "mazda",
  "mercedes-benz": "mercedes-benz",
  "mercedes-maybach": "mercedes-maybach",
  "mercury": "mercury",
  "mini": "mini",
  "mitsubishi": "mitsubishi",
  "nio": "nio",
  "neta": "neta",
  "nissan": "nissan",
  "opel": "opel",
  "peugeot": "peugeot",
  "plymouth": "plymouth",
  "polestar": "polestar",
  "pontiac": "pontiac",
  "porsche": "porsche",
  "puch": "puch",
  "radar": "radar",
  "ravon": "ravon",
  "renault": "renault",
  "samsung": "renault samsung",
  "rivian": "rivian",
  "rolls-royce": "rolls-royce",
  "rover": "rover",
  "saic": "saic",
  "saab": "saab",
  "saturn": "saturn",
  "scion": "scion",
  "seat": "seat",
  "seres": "seres",
  "shuanghuan": "shuanghuan",
  "skoda": "skoda",
  "smart": "smart",
  "ssang-yong": "ssangyong",
  "subaru": "subaru",
  "suzuki": "suzuki",
  "tank": "tank",
  "tesla": "tesla",
  "tianma": "tianma",
  "toyota": "toyota",
  "volkswagen": "volkswagen",
  "volvo": "volvo",
  "voyah": "voyah",
  "wanfeng": "wanfeng",
  "weltmeister": "weltmeister",
  "wuling": "wuling",
  "xpeng": "xpeng",
  "zx": "zx",
  "zeekr": "zeekr",
  "zotye": "zotye",
  "vaz": "ваз (lada)",
  "vis": "вис",
  "gaz": "газ",
  "zaz": "заз",
  "ij": "иж",
  "luaz": "луаз",
  "moskvich": "москвич",
  "raf": "раф",
  "retro-automobiles": "ретро-автомобили",
  "smz": "смз",
  "tagaz": "тагаз",
  "uaz": "уаз"
}